@php
    $whatsappNumber = config('services.mahecha.whatsapp_number');
    $whatsappLink = 'https://wa.me/'.$whatsappNumber.'?text='.urlencode('Habari Mahecha Furniture, ningependa kupata maelezo zaidi kuhusu bidhaa zenu.');
@endphp
<!DOCTYPE html>
<html lang="sw">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Mahecha Furniture - fenicha bora za nyumbani Ifakara. Uliza bei na oda kupitia WhatsApp.">
        <title>Mahecha Furniture | Fenicha za Ifakara</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&family=Public+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
        @vite(['resources/css/app.css', 'resources/js/app.js'])
        @livewireStyles
    </head>
    <body>
        <div class="announcement-bar"><p>Delivery ndani ya Ifakara <span aria-hidden="true">·</span> Wasiliana nasi kuthibitisha eneo</p></div>
        <header class="site-header">
            <a href="#mwanzo" class="brand" aria-label="Mahecha Furniture - mwanzo"><span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 48 48" role="img"><path d="M10 35V12h5l9 12 9-12h5v23h-6V22l-8 10-8-10v13z"/></svg></span><span><strong>Mahecha</strong><small>FURNITURE <i>·</i> IFAKARA</small></span></a>
            <nav class="desktop-nav" aria-label="Menyu kuu"><a href="#bidhaa">Bidhaa</a><a href="#huduma">Huduma</a><a href="#kwa-nini">Kwa nini sisi</a><a href="#kuhusu">Kuhusu sisi</a><a href="#mahali">Mahali tulipo</a></nav>
            <button class="mobile-menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu"><span class="sr-only">Fungua menyu</span><span aria-hidden="true">☰</span></button>
            <a class="header-cta" href="{{ $whatsappLink }}" target="_blank" rel="noopener"><span class="whatsapp-icon" aria-hidden="true">↗</span><span>Ongea nasi</span></a>
        </header>
        <nav class="mobile-menu" id="mobile-menu" aria-label="Menyu ya simu" hidden><a href="#bidhaa">Bidhaa</a><a href="#huduma">Huduma</a><a href="#kwa-nini">Kwa nini sisi</a><a href="#kuhusu">Kuhusu sisi</a><a href="#mahali">Mahali tulipo</a></nav>
        <main>
            <section class="hero" id="mwanzo">
                <div class="hero-copy"><p class="kicker"><span></span> Fenicha za Ifakara</p><h1>Nyumba nzuri huanza na <em>mbao bora.</em></h1><p class="hero-intro">Tunatengeneza fenicha zenye tabia, uimara na uzuri wa kweli kwa nyumba za Tanzania.</p><div class="hero-actions"><a class="button button-primary" href="#bidhaa">Tazama bidhaa <span aria-hidden="true">↓</span></a><a class="text-link whatsapp-button" href="{{ $whatsappLink }}" target="_blank" rel="noopener">Wasiliana nasi WhatsApp <span aria-hidden="true">↗</span></a></div><div class="hero-note"><span class="note-line"></span><span>Imetengenezwa kwa mikono Ifakara</span></div></div>
                <div class="hero-visual" aria-label="Samani za mbao za Mahecha Furniture"><div class="hero-image-wrap"><img src="https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1400&q=90" alt="Sofa ya kisasa katika sebule yenye mwanga" fetchpriority="high" decoding="async"></div><div class="hero-stamp"><span>DESIGN</span><strong>MAHECHA</strong><span>EST. 2024 · IFAKARA</span></div><div class="hero-caption"><span>Samani za kukaa</span></div></div>
            </section>
            <section class="trust-strip" id="kwa-nini" aria-label="Sababu za kuchagua Mahecha Furniture"><div class="trust-item"><span class="trust-number">01</span><div><strong>Ubora uliohakikishwa</strong><p>Mbao bora, kazi ya ustadi.</p></div></div><div class="trust-item"><span class="trust-number">02</span><div><strong>Delivery ya Ifakara</strong><p>Wasiliana nasi kuthibitisha eneo.</p></div></div><div class="trust-item"><span class="trust-number">03</span><div><strong>Lipa unapopokea</strong><p>Inapatikana kwa oda zinazokubaliwa.</p></div></div></section>
            <section class="catalog-section" id="bidhaa"><div class="section-heading"><div><p class="kicker"><span></span> Kazi zetu</p><h2>Chagua kitu cha<br><em>kuishi nacho.</em></h2></div><p class="section-lead">Tazama bidhaa zetu zenye bei, kisha agiza kupitia WhatsApp au tuulize kuhusu chaguo linalokufaa.</p></div><livewire:product-catalog /></section>
            <section class="services-section" id="huduma"><div class="section-heading"><div><p class="kicker"><span></span> Huduma zetu</p><h2>Paa imara,<br><em>nyumba salama.</em></h2></div><p class="section-lead">Mbali na fenicha, tunakusaidia kumalizia paa la nyumba yako kwa kazi safi na ya kuaminika.</p></div><div class="services-grid"><article class="service-card"><div class="service-icon" aria-hidden="true"><svg viewBox="0 0 64 64"><path d="M10 39 32 17l22 22M16 35v17h32V35M25 52V39h14v13"/></svg></div><div><p class="product-eyebrow">Huduma ya kwanza</p><h3>Kupaua</h3><p>Tunajenga na kukarabati miundo ya paa kwa umakini, vipimo sahihi na vifaa vinavyodumu.</p><a class="product-link whatsapp-button" href="https://wa.me/{{ $whatsappNumber }}?text={{ urlencode('Habari Mahecha Furniture, nahitaji huduma ya kupaua. Naomba maelezo zaidi.') }}" target="_blank" rel="noopener">Uliza kuhusu kupaua <span aria-hidden="true">↗</span></a></div></article><article class="service-card service-card-dark"><div class="service-icon" aria-hidden="true"><svg viewBox="0 0 64 64"><path d="M10 47h44M16 47l5-30h22l5 30M25 17v30M39 17v30M16 30h32"/></svg></div><div><p class="product-eyebrow">Huduma ya pili</p><h3>Kupiga bati</h3><p>Tunapiga na kufunga bati kwa mpangilio mzuri ili paa lako liwe imara, nadhifu na lisilovuja.</p><a class="product-link whatsapp-button" href="https://wa.me/{{ $whatsappNumber }}?text={{ urlencode('Habari Mahecha Furniture, nahitaji huduma ya kupiga bati. Naomba maelezo zaidi.') }}" target="_blank" rel="noopener">Uliza kuhusu kupiga bati <span aria-hidden="true">↗</span></a></div></article></div></section>
            <section class="story-section" id="kuhusu"><div class="story-image"><img src="https://images.unsplash.com/photo-1601058268499-e52658b8bb88?auto=format&fit=crop&w=1100&q=85" alt="Mtaalamu akifanya kazi ya mbao" loading="lazy"><span class="vertical-label">KAZI YA MIKONO · KAZI YA MOYO</span></div><div class="story-copy"><p class="kicker"><span></span> Kuhusu Mahecha</p><h2>Fenicha yenye<br><em>maana zaidi.</em></h2><p>Mahecha Furniture ni biashara ya fenicha kutoka Ifakara inayounganisha ujuzi wa seremala na ladha ya nyumba za kisasa. Tunatengeneza vipande vinavyokaa vizuri, vinaonekana vizuri na vinadumu.</p><p>Ukiwa na wazo maalum, tushirikishe. Tunapokea oda zinazolingana na nafasi, rangi na maisha yako.</p><a class="text-link whatsapp-button" href="{{ $whatsappLink }}" target="_blank" rel="noopener">Anza mazungumzo <span aria-hidden="true">↗</span></a></div></section>
            <section class="contact-section" id="mahali"><div class="contact-heading"><p class="kicker"><span></span> Tufikie</p><h2>Tutengeneze<br><em>nyumba yako.</em></h2></div><div class="contact-details"><div class="contact-block"><span>Tembelea</span><p>Ifakara, Mkabala na<br>Kituo cha Polisi Kibaoni</p></div><div class="contact-block"><span>Simu / WhatsApp</span><p><a href="tel:+255696410268">0696 410 268</a><br><a href="tel:+255787354818">0787 354 818</a></p></div><div class="contact-block"><span>Barua pepe</span><p><a href="mailto:denismahecha2004@gmail.com">denismahecha2004<br>@gmail.com</a></p></div><div class="contact-block"><span>Saa za kazi</span><p>Jumatatu – Jumamosi<br>9:00 AM – 6:00 PM</p></div></div><a class="button button-light" href="{{ $whatsappLink }}" target="_blank" rel="noopener">Ongea nasi WhatsApp <span aria-hidden="true">↗</span></a></section>
    </main>
        <footer class="site-footer"><a href="#mwanzo" class="brand footer-brand"><span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 48 48" role="img"><path d="M10 35V12h5l9 12 9-12h5v23h-6V22l-8 10-8-10v13z"/></svg></span><span><strong>Mahecha</strong><small>FURNITURE <i>·</i> IFAKARA</small></span></a><p>Fenicha zenye tabia, Ifakara.</p><p>© {{ date('Y') }} Mahecha Furniture</p></footer>
        <a class="floating-whatsapp" href="{{ $whatsappLink }}" target="_blank" rel="noopener" aria-label="Ongea nasi WhatsApp"><span aria-hidden="true">↗</span><strong>WhatsApp</strong></a>
        @livewireScripts
    </body>
</html>
