<div class="admin-product-page min-h-screen bg-[#f5f1e9] text-[#25251f]">
    <div class="mx-auto max-w-[1440px] px-5 pt-6 sm:px-8 lg:px-10">
        @include('livewire.admin.product-controls')
    </div>
    <main class="mx-auto max-w-[1440px] px-5 py-8 sm:px-8 lg:px-10">
        <header class="mb-8 flex flex-wrap items-end justify-between gap-5">
            <div><p class="mb-2 text-[10px] font-bold uppercase tracking-[.2em] text-[#a85335]">Mahecha Furniture / Catalog</p><h1 class="font-[Fraunces] text-4xl font-semibold tracking-tight sm:text-5xl">Bidhaa zako</h1><p class="mt-2 max-w-xl text-sm text-[#777269]">Ongeza, hariri na simamia bidhaa zinazoonekana kwa wateja kwenye website.</p></div>
            <div class="flex items-center gap-3"><a class="rounded-full border border-[#25251f]/15 bg-white px-4 py-2.5 text-xs font-bold hover:border-[#a85335]" href="{{ route('home') }}" target="_blank">Tazama website <span class="ml-1 text-base">↗</span></a><form method="POST" action="{{ route('logout') }}">@csrf<button class="rounded-full bg-[#25251f] px-5 py-2.5 text-xs font-bold uppercase tracking-wider text-white hover:bg-[#a85335]" type="submit">Ondoka</button></form></div>
        </header>

        @if (session('message'))<div class="mb-6 rounded-xl border border-emerald-700/20 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" role="status">{{ session('message') }}</div>@endif

        <div class="mb-7 grid gap-3 sm:grid-cols-3"><div class="rounded-2xl border border-[#25251f]/10 bg-white p-4"><p class="text-[10px] font-bold uppercase tracking-wider text-[#777269]">Catalog yote</p><p class="mt-2 text-2xl font-semibold">{{ $products->count() }}</p><p class="text-xs text-[#777269]">bidhaa</p></div><div class="rounded-2xl border border-[#25251f]/10 bg-white p-4"><p class="text-[10px] font-bold uppercase tracking-wider text-[#777269]">Zinapatikana</p><p class="mt-2 text-2xl font-semibold text-emerald-700">{{ $products->where('in_stock', true)->count() }}</p><p class="text-xs text-[#777269]">zinaonekana website</p></div><div class="rounded-2xl border border-[#25251f]/10 bg-[#25251f] p-4 text-white"><p class="text-[10px] font-bold uppercase tracking-wider text-[#d2a24b]">Kategoria</p><p class="mt-2 text-2xl font-semibold">{{ $products->pluck('category')->unique()->count() }}</p><p class="text-xs text-zinc-400">za bidhaa</p></div></div>

        <div class="grid items-start gap-7 xl:grid-cols-[360px_minmax(0,1fr)]">
            <section class="admin-product-form rounded-2xl border border-[#25251f]/10 bg-white p-6 shadow-[0_14px_35px_rgba(37,37,31,.06)]">
                <div class="mb-6 flex items-start justify-between gap-3"><div><p class="text-[10px] font-bold uppercase tracking-[.17em] text-[#a85335]">{{ $editingId ? 'Editing mode' : 'Quick add' }}</p><h2 class="mt-1 font-[Fraunces] text-2xl">{{ $editingId ? 'Sasisha bidhaa' : 'Ongeza bidhaa' }}</h2></div>@if ($editingId)<button class="rounded-full bg-[#f5f1e9] px-3 py-1.5 text-xs font-semibold text-[#a85335]" type="button" wire:click="cancelEdit">Ghairi</button>@endif</div>
                <form class="space-y-4" wire:submit="save">
                    <div><label class="mb-1.5 block text-xs font-bold" for="name">Jina la bidhaa</label><input id="name" class="admin-product-input w-full rounded-xl border px-3.5 py-3 text-sm" type="text" wire:model="name" placeholder="Mfano: Meza ya kulia">@error('name')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div>
                    <div class="grid grid-cols-2 gap-3"><div><label class="mb-1.5 block text-xs font-bold" for="category">Kategoria</label><select id="category" class="admin-product-input w-full rounded-xl border px-3 py-3 text-sm" wire:model="category"><option value="">Chagua</option><option value="Viti">Viti</option><option value="Meza">Meza</option><option value="Vitanda">Vitanda</option><option value="Makabati">Makabati</option></select>@error('category')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div><div><label class="mb-1.5 block text-xs font-bold" for="price">Bei (TZS)</label><input id="price" class="admin-product-input w-full rounded-xl border px-3 py-3 text-sm" type="number" min="0" step="0.01" wire:model="price" placeholder="0">@error('price')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div></div>
                    <div><label class="mb-1.5 block text-xs font-bold" for="description">Maelezo mafupi</label><textarea id="description" class="admin-product-input min-h-28 w-full rounded-xl border px-3.5 py-3 text-sm" wire:model="description" placeholder="Eleza bidhaa kwa ufupi..."></textarea>@error('description')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div>
                    <div><label class="mb-1.5 block text-xs font-bold" for="image">Picha ya bidhaa</label><label class="admin-upload flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#25251f]/20 px-4 py-5 text-center hover:border-[#a85335]" for="image"><span class="mb-1 text-2xl text-[#a85335]">+</span><span class="text-xs font-semibold">Chagua picha</span><span class="mt-1 text-[10px] text-[#777269]">PNG, JPG hadi 2MB</span><input id="image" class="hidden" type="file" wire:model="image" accept="image/*"></label>@error('image')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror</div>
                    <label class="flex items-center gap-3 rounded-xl bg-[#f5f1e9] px-3.5 py-3 text-sm"><input class="rounded border-[#25251f]/30 text-[#a85335]" type="checkbox" wire:model="in_stock"><span><strong class="block text-xs">Ipo kwenye stock</strong><small class="text-[11px] text-[#777269]">Itaonekana kwa wateja</small></span></label>
                    <button class="w-full rounded-xl bg-[#a85335] px-5 py-3.5 text-xs font-bold uppercase tracking-wider text-white shadow-sm hover:bg-[#25251f]" type="submit">{{ $editingId ? 'Sasisha bidhaa' : 'Hifadhi bidhaa' }} <span class="ml-1 text-base">↗</span></button>
                </form>
            </section>

            <section class="admin-catalog-panel overflow-hidden rounded-2xl border border-[#25251f]/10 bg-white shadow-[0_14px_35px_rgba(37,37,31,.06)]"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-[#25251f]/10 px-6 py-5"><div><p class="text-[10px] font-bold uppercase tracking-[.17em] text-[#a85335]">Live catalog</p><h2 class="mt-1 font-[Fraunces] text-2xl">Bidhaa zote</h2></div><span class="rounded-full bg-[#e7ded0] px-3 py-1.5 text-xs font-bold">{{ $products->where('in_stock', true)->count() }} zinapatikana</span></div><div class="divide-y divide-[#25251f]/10">@forelse ($products as $product)<article class="admin-product-row flex flex-wrap items-center gap-4 px-6 py-4 sm:flex-nowrap" wire:key="product-{{ $product->id }}"><div class="admin-product-thumb shrink-0">@if ($product->imageUrl())<img src="{{ $product->imageUrl() }}" alt="{{ $product->name }}">@else<span>{{ strtoupper(substr($product->category, 0, 1)) }}</span>@endif</div><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h3 class="truncate font-semibold">{{ $product->name }}</h3><span class="rounded-full bg-[#f5f1e9] px-2 py-0.5 text-[10px] font-bold text-[#777269]">{{ $product->category }}</span></div><p class="mt-1 line-clamp-1 text-xs text-[#777269]">{{ $product->description ?: 'Hakuna maelezo yaliyowekwa.' }}</p></div><div class="text-left sm:min-w-[112px] sm:text-right"><p class="font-semibold">{{ $product->price ? 'TZS '.number_format((float) $product->price) : 'Bei haijawekwa' }}</p><span class="text-[11px] font-semibold {{ $product->in_stock ? 'text-emerald-700' : 'text-red-700' }}">● {{ $product->in_stock ? 'Ipo stock' : 'Haipo stock' }}</span></div><div class="flex shrink-0 gap-2"><button class="rounded-lg border border-[#25251f]/10 px-3 py-2 text-xs font-bold text-[#a85335] hover:bg-[#f5f1e9]" type="button" wire:click="edit({{ $product->id }})">Hariri</button><button class="rounded-lg border border-red-700/15 px-3 py-2 text-xs font-bold text-red-700 hover:bg-red-50" type="button" wire:click="delete({{ $product->id }})" wire:confirm="Una uhakika unataka kufuta bidhaa hii?">Futa</button></div></article>@empty<div class="px-6 py-16 text-center"><p class="font-[Fraunces] text-2xl">Catalog bado iko tupu</p><p class="mt-2 text-sm text-[#777269]">Ongeza bidhaa yako ya kwanza kutumia form.</p></div>@endforelse</div></section>
        </div>
    </main>
</div>
